### ISSUE TITLE
Requirements for roblox-ts

### ISSUE THREAD

**Issue by osyrisrblx** [LPGhatguy/dumpling#21]
Here's an issue for a list of things that [roblox-ts](https://roblox-ts.github.io/) needs before it can adopt rodocs for it's [automated types](https://github.com/roblox-ts/types).

- [ ] **Automated JSON releases**
Need a way to hit an endpoint and get the latest JSON blob.

- [ ] **Ability to override API signatures**
The API dump does not specify specific instance types or whether or not Instances are possibly nil. This will need to be done by hand. i.e.
`Players:GetPlayerFromCharacter(character: Instance): Instance)`
to
`Player:GetPlayerFromCharacter(character: Model): Player | nil`

- [ ] **Enums #7**
- [ ] **DevHub Web Scraping #10**
This might not be necessary if the devhub JSON endpoint comes back.

**Comment by Validark** [comment]
I believe the API dump has the same issue with typing something as Instance when it should be Instance or undefined. I submitted a PR to assume it's nullable by default. It might have been the rbx-safe-types PR, when I basically changed everything, but I'm pretty sure it was before that. So that's a problem we already "solved".

**Comment by Validark** [comment]
It would be awesome if https://github.com/rodocs/docs was more comprehensive. If needed, we could get them started by scraping our TS definitions and converting to markdown files (should just need to remove the stars on the left hand side of each line).

**Comment by osyrisrblx** [comment]
> I believe the API dump has the same issue with typing something as Instance when it should be Instance or undefined.

This isn't a rule we can follow 100% of the time. For example, `Player.Character` might be nil, but `Players.LocalPlayer` should never be. (Assuming client)

**Comment by osyrisrblx** [comment]
> It would be awesome if https://github.com/rodocs/docs was more comprehensive.

Yep, that's the idea. Once this issue is resolved, we can point `@rbxts/types` to the rodocs endpoint. Then any type changes could just be in the form of PRs to rodocs/docs.

I suspect we'll need to maintain a few things that don't make sense for Rodocs, but this should be pretty minimal. (i.e. lua.d.ts, roblox.d.ts, es.d.ts, etc.)

**Comment by Validark** [comment]
You seem to be saying you want us to eventually move away from needing customDefinitions.d.ts? Is that right?

**Comment by osyrisrblx** [comment]
We may need _some_ things in there, but the goal would be to remove as much of it as possible. I'd like to offload this work to the broader community via Rodocs. Optimally, Rodocs could give us everything we need in one JSON blob.

The idea is that contributions to Rodocs would benefit other projects as well.
